name: lastfm_stack
services:
  postgres:
    image: postgres:latest
    container_name: pg
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      POSTGRES_DB: ${PGDATABASE}
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ../docker/postgres/initdb.d:/docker-entrypoint-init
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER"]
      interval: 5s
      timeout: 3s
      retries: 10

  minio:
    image: quay.io/minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports: ["9000:9000", "9001:9001"]
    volumes:
      - minio:/data
    healthcheck:
      test: ["CMD", "bash", "-c", "curl -fsS http://localhost:9000/minio/health/ready || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 20

  minio-mc:
    image: quay.io/minio/mc:latest
    depends_on: [minio]
    volumes:
      - ../docker/minio/create-buckets.sh:/usr/local/bin/create-buckets.sh:ro
    entrypoint: ["/bin/sh", "-c"]
    command: |
      /usr/local/bin/create-buckets.sh && trail -f /dev/null
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      S3_BUCKET_RAW: ${S3_BUCKET_RAW}
      S3_BUCKET_CURATED: ${S3_BUCKET_CURATED}

  vault:
    image: hashicorp/vault:latest
    container_name: vault
    volumes:
      - ../docker/vault/config.hcl:/vault/config/config.hcl:ro
      - ../docker/vault/policies:/vault/policies:ro
    cap_add: ["IPC_LOCK"]
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: ${VAULT_DEV_ROOT_TOKEN_ID}
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
    ports: ["8200:8200"]
    command: ["server", "-dev"]


  pgadmin:
    image: dpage/pgadmin4:latest
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_PASSWORD}
    ports: ["5050:80"]
    depends_on: [postgres]

volumes:
  pgdata: {}
  minio: {}
